### ISSUE TITLE
please remove usages of the `numpy/oldnumeric.h` header

### ISSUE THREAD

**Issue by rgommers** [enthought/enable#1005]
There are 4 instances of using this header left in this repo. It will be removed from NumPy at some point. I was looking at this because we're doing a build system migrating in NumPy - that will land in NumPy 1.25.0 (mid 2023)

**Comment by corranwebster** [comment]
Thanks for reporting this.  3 of the 4 uses are in code that we are hoping to deprecate, but the 4th is in a module that we'd like to continue supporting, so we'll aim to update for the next release.
