### ISSUE TITLE
ImportError: cannot import name 'ConstraintsContainer' from 'enable.api' when running python3.11

### ISSUE THREAD

**Issue by homosapien-lcy** [enthought/enable#1018]
**Problem Description**
When running some enable examples, this import error is raised

**Reproduction Steps:**
python enable/kiva/examples/kiva/compiled_path.py

**Expected behavior:**
example passed

**OS, Python version:** [MacOS, python3.8 (with or without EDM), python3.11]

**Comment by jwiggins** [comment]
Seems expected? The referenced example explicitly uses `ConstraintsContainer`.

Here's `enable.api`:
https://github.com/enthought/enable/blob/4d51db21a3cae2e316afa3c7329e35eba26ea589/enable/api.py#L283-L290

**Comment by corranwebster** [comment]
Possibly should give better feedback about needing to have Kiwi installed?

**Comment by homosapien-lcy** [comment]
Thanks, I just added PR #1019 to add more feedback to thsi error
