### ISSUE TITLE
Savage depends on `pyparsing` but not directly in dependencies

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#1040]
It likely gets pulled in by other dependencies; we should make it explicit, however.

**Comment by mdickinson** [comment]
See also #543, and enthought/chaco#858

**Comment by corranwebster** [comment]
There is now an optional "svg" dependency which requires pyparsing, and this is now required by Chaco, so I think that this is resolved.

**Comment by mdickinson** [comment]
@corranwebster Should #543 also be closed?

**Comment by corranwebster** [comment]
Not sure - "test" doesn't include pyparsing - let me check
