### ISSUE TITLE
Ignore X11 fonts on OS X

### ISSUE THREAD

**Issue by jwiggins** [enthought/enable#151]
Here's the offending code:
https://github.com/enthought/enable/blob/master/kiva/fonttools/font_manager.py#L419

This was discovered when showing a rho 'ρ' character with a Chaco `Label` using the `'modern'` (sans-serif) font. On an OS X machine with X11 installed, the X11 Vera font is used instead of the system Verdana font. On Windows, Verdana is also used. The Vera font doesn't have 'ρ' (latin characters only!), so you get a nice box glyph instead.

I think this is silly and would like to ignore X11 font directories on OS X. @rkern, do you have an opinion?

**Comment by rkern** [comment]
Yes, you are completely correct.
