### ISSUE TITLE
Travis-ci is failing on master

### ISSUE THREAD

**Issue by itziakos** [enthought/enable#170]
I think that this needs to be fixed asap so that we can be sure that there no hidden/shadowed errors in PRs

**Comment by jwiggins** [comment]
Here's the code for the exception that's been showing up:
https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L63-L66

I believe this means that PIL or Pillow is getting installed twice during the setup phase on Travis. I haven't quite sussed it out from the log file, but it appears to happen when the PIL requirement is satisfied while running setup.py.

**Comment by jwiggins** [comment]
Found it:
```
Collecting pillow>=2.4.0 (from reportlab->-r dev_requirements.txt (line 9))
Downloading Pillow-2.7.0.tar.gz (7.4MB)
```
First PIL is installed, then Pillow gets installed because reportlab requires it.

**Comment by jwiggins** [comment]
I found another problem...

`enable/tests/tools/button_tool_test_case.py` causes a SyntaxError exception on Python 2.6 because of the multiple context expressions in the with statements.
