### ISSUE TITLE
Install and update Enable package with python wheel.

### ISSUE THREAD

**Issue by duytrung** [enthought/enable#188]
Hi all,

I want to update the package Enable by downloading pre-compiled version. I couldn't find via the github "https://github.com/enthought/enable/" or Enthought github "https://github.com/enthought/enable/".

What do you recommend?

Thank you.

Kind regards

**Comment by corranwebster** [comment]
We don't currently build wheels, so you will need to build yourself if you require that.  Building for multiple different platforms (you don't say which one you need) is a non-trivial matter, and so we are not planning to start doing so.

Precompiled "egg" builds of Enable and its dependencies _are_ part of Enthought's freely available Canopy package management system (for Windows, Linuxes and OS X).  That may be an alternative option for you.

**Comment by duytrung** [comment]
Thank you corranwebster!
