### ISSUE TITLE
Many missing files in kiva.quartz in tarball

### ISSUE THREAD

**Issue by cournape** [enthought/enable#190]
At least the following are required to build `kiva.quartz`, and are missing from the sdist tarball:

```
kiva/quartz/ABCGI.pyx
kiva/quartz/CTFont.pyx
kiva/quartz/CoreFoundation.pxi
kiva/quartz/CoreGraphics.pxi
kiva/quartz/CoreText.pxi
kiva/quartz/Python.pxi
kiva/quartz/c_numpy.pxd
kiva/quartz/mac_context.c
kiva/quartz/mac_context.h
kiva/quartz/mac_context_cocoa.m
kiva/quartz/numpy.pxi
```

**Comment by jwiggins** [comment]
:weary: I thought we went through this with #130 already.

Thanks for the bug report. How do you recommend that it be fixed? Is it as simple as adding the listed files to the `MANIFEST.in` file?

**Comment by itziakos** [comment]
#240 has fixed this issue.
