### ISSUE TITLE
kiwisolver should be an optional dependency of enable 

### ISSUE THREAD

**Issue by itziakos** [enthought/enable#212]
Currently it is not possible to use enable without kiwi-solver even if the constrained layout is not used. We need to make the relationship of enable to kiwi-solver truly optional.

**Comment by jwiggins** [comment]
#421 disagrees. Shall we close this issue?

**Comment by itziakos** [comment]
> #421 disagrees. Shall we close this issue?

#421 It just makes some recommendation on the code  and does not disagree with making the related code and thus wikisolver optional.

**Comment by rkern** [comment]
#421 is suggesting that we use `kiwisolver` non-optionally to implement core Enable functionality. So yes, it does disagree with this.

**Comment by jwiggins** [comment]
I'll also add that `kiwisolver` is now a dependency of `matplotlib`, so it's perhaps not as much of a _rare bird_ as it used to be.

**Comment by itziakos** [comment]
> #421 is suggesting that we use `kiwisolver` non-optionally to implement core Enable functionality. So yes, it does disagree with this.

Since three people read the same issue and two (the majority) agree that it declares the use of the constrained layout to become universal. Then this issue can be closed.
