### ISSUE TITLE
Viewport test cases break on some test runs under Python 3

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#228]
There is an issue where the viewport test cases sometimes fail when run under Python 3 (it hasn't been observed for Python 2).  Initial investigation seems to implicate the order in which trait change events fire during object initialisation.

**Comment by mdickinson** [comment]
Sounds like dictionary order dependence again; if so, I'd expect to be able to reproduce under Python 2 under `PYTHONHASHSEED=random`.

**Comment by corranwebster** [comment]
That's my suspicion too, although I needed to check up exactly what Python 3's default was (I didn't know that they had made random default in 3.3+).  I suspect we will find more of these.
