### ISSUE TITLE
No code for the Quartz backend is provided in the source dist in pypi.

### ISSUE THREAD

**Issue by itziakos** [enthought/enable#236]
The zip files in pypi https://pypi.python.org/pypi/enable/4.5.1 do not contain any code for the Quartz kiva back-end

**Comment by itziakos** [comment]
latest versions since 4.6.0 (https://github.com/enthought/enable/pull/240) contains the cython code for the Quartz backend

**Comment by jwiggins** [comment]
This is fixed
