### ISSUE TITLE
Bug in image loading?

### ISSUE THREAD

**Issue by jdmarch** [enthought/enable#239]
User report:

> I try to load in an image file to display in chaco as per the example:
>  https://github.com/enthought/chaco/blob/master/examples/demo/basic/image_from_file.py
> 
> This fails, because it can’t read in the image. I traced that back to a problem in kiva, namely in line 1765 from kiva/agg/agg.py there’s the line
>  `Import Image as PilImage`
> 
> and I suppose there’s an `from PIL import ...` missing
> `kiva.__version__` is  '4.5.1'

**Comment by jwiggins** [comment]
Fixed in #208

It might be time for a new release...

**Comment by corranwebster** [comment]
@jdmarch If you haven't already followed up with the user, you may wish to do so now, since the release has happened.
