### ISSUE TITLE
Look at fonttools...

### ISSUE THREAD

**Issue by jwiggins** [enthought/enable#245]
... just look at it.

As pointed out in #244, the vendorized version of fonttools inside kiva is quite old. It should either be turned into an external dependency or upgraded to a newer version.

#151 is potentially related to this as well

**Comment by corranwebster** [comment]
FWIW, it looks like it might be straightforward to rip this out and replace it with https://github.com/fonttools/fonttools

The `kiva.fonttools.fontTools` library is only imported in one or two places and the new version seems to be API-compatible enough for Kiva's needs.

**Comment by jwiggins** [comment]
Excellent. Thanks for investigating!

**Comment by corranwebster** [comment]
I think we should aim to replace the fonttools code for the next major release (ie. along with the new Agg wrappers).
