### ISSUE TITLE
Bad URL in README

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#253]
Sadly github.enthought.com doesn't exist any more.  Unfortunately this is front and center of the PyPI page and the github readme.

**Comment by jwiggins** [comment]
So... 4.6.1 then?

**Comment by corranwebster** [comment]
Not immediately, but possibly soon for 4.6.1.  There are some reports that there are issues with the native scrollbar stuff under Windows, PyQt and Python 3.5 causing massive failures in the test suite.

I'll add an issue once I get the problem analyzed, but I think there may be an issue open on the Chaco repo which is related.  It would be good to try to get it fixed for a 4.6.1.

**Comment by corranwebster** [comment]
This issue is resolved.
