### ISSUE TITLE
RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'

### ISSUE THREAD

**Issue by BenMoon** [enthought/enable#262]
Cheerio,
I've just tried my first attempt on chaco. Unfortunately no luck. I'm running a Windows 7 64bit with the current WinPython distribution (because I also use guiqwt). Importing `enable.api` in ipython results in the following error:
`
import enable.api
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-565cb6091219> in <module>()
----> 1 import enable.api

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\enable\api.py in <module>()
      6 # Major package imports
      7 # TODO - Add basic comments for the names being imported from base and enable_traits
----> 8 from .base import IDroppedOnHandler, TOP, VCENTER, BOTTOM, LEFT, HCENTER, RIGHT, \
      9     TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT, str_to_font, \
     10     empty_rectangle, intersect_bounds

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\enable\base.py in <module>()
     33 from kiva.fonttools import Font
     34 
---> 35 from .colors import color_table, transparent_color
     36 
     37 # Special 'empty rectangle' indicator:

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\enable\colors.py in <module>()
    173     # Force Traits to decide on its toolkit if it hasn't already
    174     from traitsui.toolkit import toolkit as traits_toolkit
--> 175     traits_toolkit()
    176 
    177 if ETSConfig.toolkit == 'wx':

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\traitsui\toolkit.py in toolkit(*toolkits)
    160                 with provisional_toolkit(toolkit_name):
    161                     _toolkit = _import_toolkit(toolkit_name)
--> 162                     return _toolkit
    163             except (AttributeError, ImportError) as exc:
    164                 # import failed, reset toolkit to none, log error and try again

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\contextlib.py in __exit__(self, type, value, traceback)
     75                 value = type()
     76             try:
---> 77                 self.gen.throw(type, value, traceback)
     78                 raise RuntimeError("generator didn't stop after throw()")
     79             except StopIteration as exc:

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\traits\etsconfig\etsconfig.py in provisional_toolkit(self, toolkit)
    236         self.toolkit = toolkit
    237         try:
--> 238             yield
    239         except:
    240             # reset the toolkit state

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\traitsui\toolkit.py in toolkit(*toolkits)
    159             try:
    160                 with provisional_toolkit(toolkit_name):
--> 161                     _toolkit = _import_toolkit(toolkit_name)
    162                     return _toolkit
    163             except (AttributeError, ImportError) as exc:

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\traitsui\toolkit.py in _import_toolkit(name)
     81 
     82 def _import_toolkit ( name ):
---> 83     return __import__( name, globals=globals(), level=1 ).toolkit
     84 
     85 

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\traitsui\qt4\__init__.py in <module>()
     16 # import pyface.qt before anything else is done so the sipapi
     17 # can be set correctly if needed
---> 18 import pyface.qt
     19 
     20 #----------------------------------------------------------------------------

C:\Users\15604la\Downloads\WinPython-64bit-3.5.2.3Qt5\python-3.5.2.amd64\lib\site-packages\pyface\qt\__init__.py in <module>()
     42 elif qt_api != 'pyside':
     43     raise RuntimeError("Invalid Qt API %r, valid values are: 'pyqt' or 'pyside'"
---> 44                        % qt_api)

RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'`

Sorry, I don't get the formatting properly done. I'm sure pyqt is installed, is there. Did I miss anything and there's an easy way to solve this?

Thank you very much
Best
Ben

**Comment by corranwebster** [comment]
Hi, Ben.  Enable currently runs with Qt4 only, not with Qt5 yet (it is waiting on TraitsUI to support Qt5 first).  You will at a minimum need to ensure that you have Qt4 and PyQt available in your environment and possibly set the `QT_API` environment variable to point to `pyqt` rather than `pyqt5`.  The blocker for Qt5 support is being able to support reliable continuous integration testing.

Enable on Python 3 is very new, so you may potentially find some other issues (there are some very recent reports of bitmap images not working correctly in Windows under Python 3), and if you want to use Chaco, you will need to install directly from github.

I'm going to close this issue, but have opened a more general "Support Qt5" ticket #263.

If you run into any more issues, please don't hesitate to let us know.
