### ISSUE TITLE
Support for Qt5

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#263]
There are three areas where work needs to be done:

- [ ] the QPainter backend for Kiva
- [ ] the Qt toolkit package in Enable
- [ ] support for CI

Much of this work is just changing the location of imports, and may even be trivial once Pyface supports Qt5.  The CI issue is more significant, as attempts to built a working Qt5 environment on TravisCI have been unsuccessful, particularly in containerized environments.  There is no point in claiming Qt5 support without it being tested on every PR.

See also #262.

**Comment by corranwebster** [comment]
Update from a bit of ad-hoc experimentation and it looks like with Pyface 6.0 things mostly work. There are two things which need work:

- the QMouseWheelEvent class API has changed to a much better one, but it will need a re-think of the API for mousewheel events
- the embedded native scrollbar isn't being disposed of correctly in some tests - need to check lifecycles

Mostly it's just a matter of setting up CI testing correctly.

**Comment by jwiggins** [comment]
Relatedly, `Qt::MouseButton` has many more possible values which will need to go into `BUTTON_NAME_MAP`

**Comment by danieljfarrell** [comment]
Just to be clear. Enable does not yet support PyQt5? I'm building a runtime with chaco and enable and running into issues. I may downgrade the runtime to PyQt4 so I can use Chaco.

**Comment by corranwebster** [comment]
I think that this issue should have been closed by #302   There may be outstanding issues, but the fundamentals should be fine.

**Comment by danieljfarrell** [comment]
Ahh OK. I’m getting a weird issue with PyQt5 but with Chaco. I though it was related to enable but maybe not. I will post in the project pages there.

**Comment by corranwebster** [comment]
Please do open an issue in Chaco.  It may end up being a bug in Enable, but it's better to start where you are seeing it.
