### ISSUE TITLE
Ensure support for Pillow 3.x and 4.x

### ISSUE THREAD

**Issue by itziakos** [enthought/enable#271]
A number of methods have been deprecated/renamed and changed behaviour since 2.x.x. So It is highly probable that kiva will not work with Pillow >= 3.x

for example:
- https://pillow.readthedocs.io/en/4.1.x/releasenotes/3.0.0.html#deprecated-methods
- https://pillow.readthedocs.io/en/4.1.x/releasenotes/3.4.0.html#image-core-open-ppm-removed
- https://pillow.readthedocs.io/en/4.1.x/releasenotes/4.0.0.html#image-core-stretch-removed
- https://pillow.readthedocs.io/en/4.1.x/releasenotes/4.1.0.html#removed-deprecated-items
- https://pillow.readthedocs.io/en/4.1.x/releasenotes/4.1.0.html#closing-files-when-opening-images

**Comment by rkern** [comment]
It's likely only the `tostring()` and `fromstring()` methods that cause issues. We already have a compatibility layer in place in `kiva.compat`. I think only `kiva/tests/agg/test_image3.py` misses using that.

**Comment by jwiggins** [comment]
Not only that, but `kiva/tests/agg/test_image3.py` appears to be dead code. We should probably just ditch it.

**Comment by itziakos** [comment]
Actually we already run tests using PIL 4.0.0 (https://travis-ci.org/enthought/enable/jobs/209455117#L330)
