### ISSUE TITLE
Celiagg backend doesn't save images correctly

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#304]
From enable, when I call `save` to put the contents of a celiagg gc into a .png file, I get this:

![component_ex](https://user-images.githubusercontent.com/600761/40582606-41151b8e-6173-11e8-8616-7d23b6bcc647.png)

where if I use the old agg backend (or indeed anything else), I get this:

![component_ex](https://user-images.githubusercontent.com/600761/40582611-6242d42c-6173-11e8-8a7c-fb25c1dcf4f3.png)

which is what I would expect based on the colors, etc. I was using.

Based on a little experimentation, the [channel shuffling](https://github.com/enthought/enable/blob/master/kiva/celiagg.py#L748) doesn't seem to be needed

**Comment by rkern** [comment]
That method needs to check what `self.pix_format` before it does anything, since the `pix_format` is a user's choice and may not be `rgba32` (or `bgra32`, which is what it is assuming incorrectly now).
