### ISSUE TITLE
wx.WXK_NEXT and wx.WXK_PRIOR not defined in wxpython 4.0.1

### ISSUE THREAD

**Issue by will133** [enthought/enable#307]
In enable/wx/constants.py it seems like the wx.WXK_NEXT and wx.WXK_PRIOR is still used.

**Comment by corranwebster** [comment]
See the comment in your TraitsUI issue.  We are a long way from WxPython 4 support in Enable.

**Comment by kitchoi** [comment]
This is now fixed by #403
Closing.
