### ISSUE TITLE
Use unittest.mock with Python 3 instead of 3rd party mock

### ISSUE THREAD

**Issue by ievacerny** [enthought/enable#314]
Using EnableTestAssistant requires additional install. Is there a specific reason for this?

https://github.com/enthought/enable/blob/b2c053110eb8bb008cae745954f3db330991ad9b/enable/testing.py#L3

**Comment by corranwebster** [comment]
It's probably not in the standard list of dependencies because it is only needed when running tests.  Possibly Enable should have an `extras_require` for `testing` which includes `mock`.

And of course under Python 3 we should be importing `unittest.mock`...

**Comment by jvkersch** [comment]
> And of course under Python 3 we should be importing unittest.mock...

Agreed. This came up while using the `EnableTestAssistant` on a Python 3 project, for which we rely on the unittest mock. Installing the 3rd party mock just to use the test assistant is somewhat bothersome...

Would it make sense to have a check somewhere (possibly in `enable.testing`) to conditionally import the right version, something like
```python
if six.PY3:
    from unittest import mock
else:
    import mock
```
and then replace all bare `from mock import bla` by something like `from enable.testing import mock; mock.bla`?

**Comment by mdickinson** [comment]
Nitpick: I'd prefer:
```
try:
    from unittest import mock
else:
    import mock
```
on that basis that that's testing for what you actually want, rather than using the version as a proxy. And it doesn't need a `six` import.

**Comment by corranwebster** [comment]
@ievacerny if you would like to make a PR to fix this I'm sure we could get it merged quickly - it wouldn't solve the problem for the project you are working on since we're not about to do a release of Enable, but it would be good to have it there for the next release.

**Comment by ievacerny** [comment]
I assume there's more than one place where the changes would have to be made and I don't think I know Enable code well enough to fix this.

**Comment by mdickinson** [comment]
@ievacerny Have you been introduced to the `grin` tool at any point?  There are indeed multiple places where the change would have to be made, but `grin` makes it easy to find all the places where mock is imported.

```
taniyama:enable mdickinson$ grin "import mock|from mock"
./enable/testing.py:
    3 : from mock import Mock
./enable/tests/test_assistant_test_case.py:
    1 : import mock
./enable/tests/tools/apptools/commands_test_case.py:
   14 : from mock import MagicMock
./enable/tests/tools/apptools/move_command_tool_test_case.py:
   14 : from mock import MagicMock
./enable/tests/tools/apptools/resize_command_tool_test_case.py:
   14 : from mock import MagicMock
./enable/tests/tools/apptools/undo_tool_test_case.py:
   14 : from mock import MagicMock
./enable/tests/wx/mouse_wheel_test_case.py:
    4 : from mock import MagicMock
./kiva/testing.py:
    3 : from mock import Mock
```

**Comment by mdickinson** [comment]
I should have mentioned that `grin` is just an `edm install grin` away ...

**Comment by ievacerny** [comment]
Ok, will make a PR later today
