### ISSUE TITLE
Upgrade Cython version for Python 3.7 compatibility

### ISSUE THREAD

**Issue by sputnick1124** [enthought/enable#316]
Basically a duplicate of https://github.com/cython/cython/issues/1955 which has propagated to here. Using cython==0.28.5 to generate `_cython_speedups.cpp` (https://github.com/sputnick1124/enable/commit/eee418d83a3828a1fe5a86d419788cd3b40365b1) builds fine  on 3.7.

**Comment by sputnick1124** [comment]
Sister issue for [chaco](https://github.com/enthought/chaco): https://github.com/enthought/chaco/issues/426

**Comment by silverjam** [comment]
This should be fixed by #336

**Comment by sputnick1124** [comment]
Thanks!
