### ISSUE TITLE
Location of 'X11-devel' package for enable dependencies 

### ISSUE THREAD

**Issue by ScottA38** [enthought/enable#328]
I am having some trouble installing Enable on Ubuntu - I am not usually that involved with packages and package management so if it is obvious go steady please.

I have created a virtualenv for the install and have installed everything except for the X11-devel dependency, which I can't find - anywhere: Ubuntu packages search, PyPi and Github (the only thing on there is something with the same name but is a deleted repository.

**Comment by stevenjkern** [comment]
I don't have an Ubuntu installation handy to confirm, but `sudo apt install libx11-dev` should be install the right libraries.

**Comment by jwiggins** [comment]
Our CI runs install `libglu1-mesa-dev`, which results in the following being installed (as of Ubuntu 16.04):
- libdrm-dev
- libgl1-mesa-dev
- libglu1-mesa
- libglu1-mesa-dev
- libx11-xcb-dev
- libxcb-dri2-0-dev
- libxcb-dri3-dev
- libxcb-glx0-dev
- libxcb-present-dev
- libxcb-randr0
- libxcb-randr0-dev
- libxcb-shape0-dev
- libxcb-sync-dev
- libxcb-xfixes0-dev
- libxdamage-dev
- libxfixes-dev
- libxshmfence-dev
- libxxf86vm-dev
- mesa-common-dev
- x11proto-damage-dev
- x11proto-dri2-dev
- x11proto-fixes-dev
- x11proto-gl-dev
- x11proto-xf86vidmode-dev
