### ISSUE TITLE
Matching TTF fonts isn't working well

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#391]
Several problems with the algorithm:

- [ ] ttfFontProperties looks into the TFFont to find the 'sfnt4' string with styling information.  It then does very dumb matching for key phrases, such as "italic", but doesn't normalize case, doesn't account for phrases which are sub-phrases of other phrases (eg. "bold" in "demibold"), and could get mismatches if a phrase is part of the name of the font (eg. "book" or "roman").
- [x] when matching .ttc files we are only returning the file, not the index of the font in the .ttc file.  FreeType2 needs this index to be able to find the correct font.  Currently the API has no way of even passing this information through to the Agg/Celiagg.

**Comment by jwiggins** [comment]
It'll take some time for this to bubble out, but:
```python
╰$ edm run -- ipython
Python 3.6.9 |Enthought, Inc. (x86_64)| (default, Feb 25 2020, 20:28:43) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from kiva.fonttools import Font                                         

In [2]: Font("Times New Roman", style=0).findfont()                             
Out[2]: '/Library/Fonts/Times New Roman.ttf'

In [3]: Font("Times New Roman", style=1).findfont()                             
Out[3]: '/Library/Fonts/Times New Roman Bold.ttf'

In [4]: Font("Times New Roman", style=2).findfont()                             
Out[4]: '/Library/Fonts/Times New Roman Italic.ttf'

In [5]: Font("Times New Roman", style=3).findfont()                             
Out[5]: '/Library/Fonts/Times New Roman Bold Italic.ttf'
```

**Comment by jwiggins** [comment]
There are still issues with parsing of the styling information. #605 only covered the face index bits of TTC files.
