### ISSUE TITLE
range expects an int in argument, but gets a float in enable/kiva/agg/freetype2/src/tools/docmaker/tohtml.py

### ISSUE THREAD

**Issue by pbrod** [enthought/enable#396]
range expects an int in argument on line 521, but gets float from non-floor division (change to // for floor division in Python 3  otherwise it will crash on passing a float): 

https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/kiva/agg/freetype2/src/tools/docmaker/tohtml.py#L512-L522

**Comment by aaronayres35** [comment]
@jwiggins you mentioned in PR #457 that the relevant file here is vendored code. you also mentioned in this comment: https://github.com/enthought/enable/pull/401#issuecomment-735862671 some fixes were explicitly avoided which seems to include a fix to this issue. Should we simply close this issue then?

**Comment by jwiggins** [comment]
Closing. This is vendored code.

**Comment by kitchoi** [comment]
For reference, the particular `tohtml` module is not used by enable/kiva. It came with the distribution of freetype2.
