### ISSUE TITLE
Examples does not work correctly

### ISSUE THREAD

**Issue by pbrod** [enthought/enable#400]
For example when running [examples/demo.py](https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/examples/demo.py#L25) and clicking on the "Example"->"Savage"->"Toggle demo" the window does not show in the demo tab, but rather as a standalone window.
The "Example"->"Savage"->"Static image"  or "Example"->"Savage"->"Buttons on canvas" does not show at all. 

In this test I am using the wx backend and:
Operating system: Windows 10 64bit
wxPython version & source: wxpython 4.0.7.post2 (https://anaconda.org/conda-forge/wxpython)
Python version & source: Python 3.7.4 (default, Aug 9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] (Anaconda)

**Comment by corranwebster** [comment]
wxPython 4 is not yet supported by Enable - support is still working its way up through TraitsUI before we get to fixing wxPython support for Enable - it may be some months before we get to it.

Please try again with WxPython 3.

Any help you are willing to provide for wxPython 4 support would be appreciated

**Comment by pbrod** [comment]
Yes, I am working on a patch for it now.

**Comment by corranwebster** [comment]
Thank you!

**Comment by pbrod** [comment]
Also the player_pause.svg and player_play.svg are missing from the examples directory.
