### ISSUE TITLE
Missing copyright headers

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#409]
The recommended copyright header is 

```
# (C) Copyright 2005-2020 Enthought, Inc., Austin, TX
# All rights reserved.
#
# This software is provided without warranty under the terms of the BSD
# license included in LICENSE.txt and may be redistributed only under
# the conditions described in the aforementioned license. The license
# is also available online at http://www.enthought.com/licenses/BSD.txt
#
# Thanks for using Enthought open source!
```

**Comment by corranwebster** [comment]
I would go with the header that Traits uses.

**Comment by rahulporuri** [comment]
ref : https://github.com/enthought/traits/blob/e16be1004bde938f969895b543cae01317fd2756/traits/api.py#L1-L9

Note that once the headers are updated, it will be good to also include the copyright_header flake8 checker https://github.com/enthought/traits/tree/master/copyright_header to ensure that the copyright headers are kept up to date.
