### ISSUE TITLE
Drop Python 2 Support

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#415]
The next major release of Enable should drop support for Python 2 and Python 3.5 and lower.

**Comment by rahulporuri** [comment]
@aaronayres35 is this complete now?

**Comment by aaronayres35** [comment]
> @aaronayres35 is this complete now?

I believe so (or at least very close).  I was planning to do one final sweep through to make sure there wasn't anything I missed.  Will do that this afternoon and close the issue after that if that works with you?  @rahulporuri

**Comment by rahulporuri** [comment]
>  Will do that this afternoon and close the issue after that if that works with you?

SGTM.
