### ISSUE TITLE
Contribute examples to the etsdemo application

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#436]
The enable GitHub repository has a number of examples - https://github.com/enthought/enable/tree/master/examples. For the upcoming release of the enable package, it would be useful to contribute said examples to the etsdemo application.

**Comment by aaronayres35** [comment]
Note also this file:
https://github.com/enthought/enable/blob/master/examples/demo.py

and from traitsui:
https://github.com/enthought/traitsui/blob/a2ad46405b5d876ff098bcc978371ab5e8855e8d/traitsui/extras/_demo_legacy.py#L18-L24

Once we contribute examples to etsdemo, I believe we will want to delete the file linked above.
