### ISSUE TITLE
Clean up Enable/Kiva setup.py

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#440]
Kiva in particular has a highly idiosyncratic usage of `setup.py` with nested `setup.py` files in sub modules, as well as custom distutils commands.

We should clean this up so that there is either a single `setup.py` (preferred), or one for Kiva and one for Enable.

In particular, we need to get rid of these subsidiary setup.py files:

https://github.com/enthought/enable/blob/master/kiva/setup.py
https://github.com/enthought/enable/blob/master/kiva/quartz/setup.py
https://github.com/enthought/enable/blob/master/kiva/agg/setup.py

**Comment by jwiggins** [comment]
You'll quickly find out how fragile that whole house of cards is. I'd prioritize #392 since it intersects this and you'll likely want to start from clear(er?) build instructions for each of the extensions.
