### ISSUE TITLE
Document behaviour of DragTool end_drag_on_leave

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#445]
`end_drag_on_leave` only has effect if `capture_mouse` is `False` (if the mouse is captured it never leaves the component).  This may be confusing behaviour, although it is reasonable when the details are thought through.  Probably best to add to this as a note to this comment:

https://github.com/enthought/enable/blob/933fc55327f4f95c97cfeb9d4504fb1f015020c2/enable/tools/drag_tool.py#L19-L20

**Comment by jwiggins** [comment]
Is this closed by #452?

**Comment by notmatthancock** [comment]
Ah, sorry. I did not see this issue when I created https://github.com/enthought/enable/issues/451 . Yes, this was closed by #452.
