### ISSUE TITLE
Cannot send "mouse move" with left/right down with EnableTestAssistant

### ISSUE THREAD

**Issue by notmatthancock** [enthought/enable#460]
As far as I can tell, the EnableTestAssistant only provides methods for creating "drag over" DragEvents, but does not provide the ability to create a mouse-move MouseEvent with left_down attribute set to True.

This seems like a straight-forward extension of EnableTestAssistant.mouse_move to include `left_down` and `right_down` keyword arguments to be included in the mouse event that is created in body of the function:

https://github.com/enthought/enable/blob/4db18d287f14bc7e68ac10a74d488485d6ca78b4/enable/testing.py#L275-L276

This functionality would be useful because (for example) the DragTool depends on mouse move events where the event has {left,right}_down set to True:

https://github.com/enthought/enable/blob/55fc728baf4f1f8f6c94a833ed251962fa8cfd04/enable/tools/drag_tool.py#L146-L148

**Comment by notmatthancock** [comment]
Unfortunately no. The definition of `mouse_move` call to `create_mouse_event` does feed anything about mouse button up/down status. `press_move_release` essentially implements the various helpers in sequence, so its behavior is no different.

Example:

```python
from enable.api import Component
from enable.testing import EnableTestAssistant


class MyComponent(Component):

    def normal_left_down(self, event):
        print(event.left_down)

    def normal_mouse_move(self, event):
        print(event.left_down)


assistant = EnableTestAssistant()
component = MyComponent(bounds=[100, 100])
assistant.mouse_down(component, 50, 50, button='left')
assistant.mouse_move(component, 50, 50)
assistant.mouse_move(component, 50, 75)
```
prints
```
True
<undefined>
<undefined>
```

**Comment by aaronayres35** [comment]
> Unfortunately no. The implementation of `mouse_move` calls to `create_mouse_event` without feeding anything about mouse button up/down status. `press_move_release` essentially implements the various helpers in sequence, so its behavior is no different.
> 

I see now, thank you! I was confused as this test was passing:
```
def test_mouse_move_after_mouse_down(self):
        test_assistant = EnableTestAssistant()
        component = Component(bounds=[100, 200])
        test_assistant.mouse_down(component, x=0, y=0)
        event = test_assistant.mouse_move(component, 10, 20)

        self.assertEqual(event.x, 10)
        self.assertEqual(event.y, 20)
        # left_down from calling mouse_dwn is carried into mouse move event
        self.assertTrue(event.left_down)
```
a `print(event.left_down)` reveals it is actually`<undefined>` which evaluates to `True` 🤦 .

Thank you for the example!

**Comment by notmatthancock** [comment]
> a print(event.left_down) reveals it is actually<undefined> which evaluates to True facepalm .

Eek. I think I recall some discussion on traits recently around the truthiness of <undefined>. I don't recall exactly where the discussion took place, but it might be a good example to show.

**Comment by mdickinson** [comment]
@aaronayres35 Could you track down where that `undefined` is coming from? Is Enable deliberately and consciously providing an undefined value here, or is this an artifact of general Traits machinery?

**Comment by aaronayres35** [comment]
> @aaronayres35 Could you track down where that `undefined` is coming from? Is Enable deliberately and consciously providing an undefined value here, or is this an artifact of general Traits machinery?

@mdickinson the `left_down` trait on a `MouseEvent` object is a `Readonly` trait:
https://github.com/enthought/enable/blob/ba6f24669192eb27c3a3545508b7b652d2f46f8f/enable/events.py#L136
which has a default of `Undefined`:
https://github.com/enthought/traits/blob/2b62cd9b39bcb9e4998eeab0b32a4e3127b3df66/traits/trait_types.py#L992-L1009
