### ISSUE TITLE
Clean-up Imports 

### ISSUE THREAD

**Issue by aaronayres35** [enthought/enable#471]
These are directly lifted from https://github.com/enthought/enable/blob/master/TODO.txt

- [x] Clean-up the failing import of enthought.freetype in
  kiva.trait_defs.ui.wx.kiva_font_editor.
- [x] Clean-up imports of enable (I mean NOT enable2) done in:
    enable2/traits/ui/wx/enable_rgba_color_editor.py
- [ ] Clean-up direct imports of traitsui.wx

The first two I believe are no longer relevant (?)

**Comment by rahulporuri** [comment]
> Clean-up direct imports of traitsui.wx

I'm not entirely sure what you mean by this. Do you mean that we should use the `toolkit` object to get the relevant object, instead of importing it manually from the specific toolkit?

**Comment by aaronayres35** [comment]
> > Clean-up direct imports of traitsui.wx
> 
> I'm not entirely sure what you mean by this. Do you mean that we should use the `toolkit` object to get the relevant object, instead of importing it manually from the specific toolkit?

TBH I'm not entirely sure either, this was directly pulled from a TODO.txt file that hadn't been touched in a few years:
https://github.com/enthought/enable/blob/118a04a8a92d79bcef71fee8c55ee0aad6a07e07/TODO.txt

Going through `toolkit_object` from traitsui seems to make sense to me though and is probably a behavior we are trying to encourage?
