### ISSUE TITLE
Kill test with etsdevtools dependency 

### ISSUE THREAD

**Issue by aaronayres35** [enthought/enable#483]
As mentioned in this comment: https://github.com/enthought/enable/pull/475#discussion_r539139527, the test https://github.com/enthought/enable/blob/master/kiva/agg/tests/test_gcmem.py should be deleted.

**Comment by rahulporuri** [comment]
@aaronayres35  the ^ link is broken.

**Comment by aaronayres35** [comment]
> @aaronayres35 the ^ link is broken.

Thanks, should be fixed now
