### ISSUE TITLE
Make Kiva Explorer demo a popup

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#509]
Rather than having Kiva explorer compressed into a tab, it probably makes sense to have it come in as a popup.  This is just a matter of changing:

https://github.com/enthought/enable/blob/2ae4f5c3f268d6f8e0de18f3022ba3cb271f5158/kiva/examples/kiva/kiva_explorer.py#L129-L132

to something like:
```
popup = ScriptedComponentView()

if __name__ == '__main__':
    popup.configure_traits()
```

This is not perfect, but better than what we have now.

**Comment by corranwebster** [comment]
@aaronayres35 Do you want to try this approach since you are working with the Enable demos?

**Comment by aaronayres35** [comment]
> @aaronayres35 Do you want to try this approach since you are working with the Enable demos?

Yep, will do! thanks
