### ISSUE TITLE
Kiva API documentation for quartz depends on the OS platform at built-time

### ISSUE THREAD

**Issue by kitchoi** [enthought/enable#533]
The API documentation is automatically generated, and when it is built on an OSX machine, one gets the following sections:
![Screenshot 2021-01-07 at 11 54 03](https://user-images.githubusercontent.com/3673984/103889918-1ed2e980-50df-11eb-9dc3-2f4f001bb11a.png)

It is clear that the documentation depends on the platform and Python version when it was built. I haven't tested, but I bet these sections are absent if the documentation was built on a Windows machine.

At the very least, the "cpython-39" bits are unexpected.

**Comment by rahulporuri** [comment]
This isn't entirely true. I just built the docs on windows (using edm and edmtool-based env) and i see the following. I'm not sure why the `.cpython-39-darwin module`s get created on cpython 39 though.

![kiva-api-quartz](https://user-images.githubusercontent.com/1926457/104003567-76825b00-519a-11eb-82a1-022ca4024483.png)

**Comment by rahulporuri** [comment]
i'm closing this issue because we are not shipping api docs for any of the kiva backends - the `AbstractGraphicsContext` API is what end users should be relying on - not the implementation details of the various backends.

**Comment by rahulporuri** [comment]
Sorry. I opened #696.
