### ISSUE TITLE
API for adding application-specific fonts

### ISSUE THREAD

**Issue by rkern** [enthought/enable#555]
There is a need for an application to provide one or more fonts that are to be used in the application, particularly for Chaco labels. For example, supporting CJK languages across platforms can benefit by providing a single suitably-licensed font and specifying that the appropriate `preferred_fonts` category uses it.

One can currently hack through the implementation details of `kiva.fonttools.font_manager` to accomplish this, but there is a need for a blessed, documented API to accomplish this.

**Comment by corranwebster** [comment]
This will probably require more than just modifying the `kiva.fonttools` code, as a most of the Kiva backends just take the name of the font and then use their own internal font discovery mechanisms to resolve it (eg. `QPainter` backend will use Qt font discovery).

**Comment by jwiggins** [comment]
It might be worth checking if [`QFontDatabase.addApplicationFont`](https://doc.qt.io/qt-5/qfontdatabase.html#addApplicationFont) can help here.

**Comment by jwiggins** [comment]
@rahulporuri We should consider adding this to 5.1.0

**Comment by jwiggins** [comment]
`QFontDatabase.addApplicationFont` works as expected with the QPainter kiva backend. As was already pointed out, there will need to be matching changes in the `kiva.fonttools` code in order to work with other backends.

**Comment by jwiggins** [comment]
[`wx.Font.AddPrivateFont`](https://docs.wxpython.org/wx.Font.html#wx.Font.AddPrivateFont) exists as well. It has some weird caveats, but since Wx support is supplied on a best effort basis...
