### ISSUE TITLE
Place Kiva docs before Enable docs?

### ISSUE THREAD

**Issue by aaronayres35** [enthought/enable#603]
Since `Kiva` is the lower level library, it might make sense to have the documentation set up so that the kiva docs appear first in the table of contents and then the `Enable` docs follow (enable builds on kiva so good to understand kiva first?).  I could however imagine arguments for leaving it as is. 

This is a very minor issue, but trivial to fix if we decide to do so.

**Comment by jwiggins** [comment]
I feel like the Kiva API is more commonly encountered than the Enable API, so I agree with this suggestion.
