### ISSUE TITLE
Kiva: clean up Kiva Interface Quick Reference

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#618]
The last section of the current Kiva documentation needs clean-up: https://github.com/enthought/enable/blob/d237ea4fdfe9788b5422c9ae37e33c111b15d04d/docs/source/kiva.rst#kiva-interface-quick-reference

- it isn't clean .rst
- a lot of it could be replaced with API documentation
- there is a place for a high-level overview of the core API methods of the "GraphicsContext interface" (perhaps pointing at the `AbstractGraphicsContext` API docs).

**Comment by jwiggins** [comment]
Some of this was done in #639

**Comment by corranwebster** [comment]
This looks good to close.
