### ISSUE TITLE
draw_rect behaves weirdly with QPainter backend

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#657]
|agg|QPainter|
|---|---|
|<img width="256" alt="kiva agg draw_rect 2x" src="https://user-images.githubusercontent.com/1926457/109619792-1623f000-7b31-11eb-90e4-b5590aba5d9c.png">|<img width="256" alt="qpainter draw_rect 2x" src="https://user-images.githubusercontent.com/1926457/109619815-18864a00-7b31-11eb-900d-cae1da311d98.png">|

The above images have been generated using the new `enable.gcbench` on windows with PyQt5.

**Comment by jwiggins** [comment]
You've got this all wrong. QPainter has the erroneous output, not AGG.

**Comment by rahulporuri** [comment]
> You've got this all wrong. QPainter has the erroneous output, not AGG.

Corrected. Sorry.
