### ISSUE TITLE
Add gradients to the benchmark suite

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#664]
Add Linear Gradients and Radial Gradients methods in the Benchmark Suite.

**Comment by jwiggins** [comment]
The graphics context methods `linear_gradient` and `radial_gradient` are basically special versions of `set_fill_color`. A good exercise of these methods would be to create a path with moderate complexity and then fill it will a gradient.

Or if you really want to show how inconsistent the different backends are:
* Set a gradient
* Set the text drawing mode to FILL_STROKE
* Draw some text
