### ISSUE TITLE
QPainter arc() method doesn't handle the flipped coordinate system

### ISSUE THREAD

**Issue by jwiggins** [enthought/enable#683]
When running the `draw_path_linear_gradient` benchmark, QPainter stands out for drawing the wrong thing:
<img alt="qpainter draw_path_linear_gradient_2x" src="https://user-images.githubusercontent.com/587491/110138043-d7609500-7dd1-11eb-8646-3d8e1590d462.png" width="512" height="512">

My working theory is that the flipped coordinate system used by the backend (since QPainter normally has a top-left origin) is not being accounted for in the `arc` method (and possibly `arc_to`?).

**Comment by corranwebster** [comment]
This is fixed by #970.
