### ISSUE TITLE
Pin traits>=6.2.0

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#733]
Now that we are in the middle of moving from `on_trait_change` to `observe`, we need to enforce `traits>=6.2.0` in our dependencies. This is a release blocker for the 5.1.0 enable release (ref #719 )

**Comment by jwiggins** [comment]
What needs to be done here? A change to `__requires__`?

**Comment by rahulporuri** [comment]
> A change to __requires__?
yep. that's all.
