### ISSUE TITLE
Should `CompiledPath` and `font_metrics_provider` be added to enable.api

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#772]
`CompiledPath` and `font_metrics_provider` aren't available via `enable.api` at the moment and I don't see a good reason why it shouldn't be. There are a few places in `chaco` which do `from enable.compiled_path import CompiledPath` and `from enable.font_metrics_provider import font_metrics_provider`.

Ref https://github.com/enthought/chaco/search?q=%22enable.compiled_path%22 and https://github.com/enthought/chaco/search?q=font_metrics_provider

**Comment by rahulporuri** [comment]
@jwiggins do you think it'll be a problem if we force toolkit selection if anyone imports anything from `enable.api`?

**Comment by jwiggins** [comment]
`enable.colors`, which is imported from `enable.api`, is already forcing toolkit selection at import time.

**Comment by jwiggins** [comment]
As long as that was done deliberately (if it's even possible to find out now), then I think it's OK to add `CompiledPath` and `font_metrics_provider`

**Comment by rahulporuri** [comment]
> As long as that was done deliberately (if it's even possible to find out now),

Sadly, this goes back all the way https://github.com/enthought/enable/commit/b3420c3108ac731e6cba422c69f51a30ff43b0c9 so we have no way of knowing if it was deliberate or not

**Comment by jwiggins** [comment]
Well in that case it's de facto OK.
