### ISSUE TITLE
Should `chaco.scatter_markers` be deprecated and removed?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#773]
https://github.com/enthought/chaco/blob/c758a65222a2caef9a3d2c074ae9dd5775a3a77e/chaco/scatter_markers.py

It looks like the contents of `chaco.scatter_markers` have been moved to `kiva` and `enable`. We should consider deprecating and removing `chaco.scatter_markers`.

**Comment by aaronayres35** [comment]
closed by https://github.com/enthought/chaco/pull/677 which removed the module in chaco
