### ISSUE TITLE
Consider moving "enable.example_*" modules into "enable.examples" submodule

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#793]
The following modules are used only by the examples so we should consider moving them into `enable.examles` submodule instead of letting them live in the top-level `enable` namespace.

- [`enable.example_application`](https://github.com/enthought/enable/blob/3d138a235547240c98ed8aba1046a3f1c016d42b/enable/example_application.py)
- [`enable.example_canvas`](https://github.com/enthought/enable/blob/3d138a235547240c98ed8aba1046a3f1c016d42b/enable/example_canvas.py)
- [`enable.example_support`](https://github.com/enthought/enable/blob/3d138a235547240c98ed8aba1046a3f1c016d42b/enable/example_support.py)

**Comment by aaronayres35** [comment]
Note this may be a breaking change outside of enable, for instance in chaco there are multiple places where we do 
`from enable.example_support import DemoFrame, demo_main`
