### ISSUE TITLE
Remove deprecated draw methods in "Component" and "Container"

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#794]
https://github.com/enthought/enable/blob/3d138a235547240c98ed8aba1046a3f1c016d42b/enable/component.py#L344-L350

https://github.com/enthought/enable/blob/3d138a235547240c98ed8aba1046a3f1c016d42b/enable/container.py#L383-L392

https://github.com/enthought/enable/blob/3d138a235547240c98ed8aba1046a3f1c016d42b/enable/container.py#L597-L616

https://github.com/enthought/enable/blob/3d138a235547240c98ed8aba1046a3f1c016d42b/enable/container.py#L618-L636

**Comment by aaronayres35** [comment]
ref: #781
