### ISSUE TITLE
ColorPicker is used but no longer exists in code base

### ISSUE THREAD

**Issue by aaronayres35** [enthought/enable#815]
searching the code base for `ColorPicker` the only results are https://github.com/enthought/enable/blob/21c299e1229d74e9db701487a613934e332a7225/enable/trait_defs/ui/wx/enable_rgba_color_editor.py#L20 and https://github.com/enthought/enable/blob/21c299e1229d74e9db701487a613934e332a7225/enable/trait_defs/ui/wx/enable_rgba_color_editor.py#L139

but I dont see the class defined anywhere

**Comment by rahulporuri** [comment]
I can't find any users of `enable.ColorPicker` on GitHub - https://github.com/search?q=%22from+enable+import+ColorPicker%22&type=code and https://github.com/search?q=%22enable.ColorPicker%22+extension%3Apy&type=code

I couldn't find any users of `enable_rgba_color_editor` either - https://github.com/search?p=1&q=%22enable_rgba_color_editor%22+extension%3Apy&type=Code - so i think we can nuke that module.

From the looks of it, this actually got moved into traitsui as the color editor module.
