### ISSUE TITLE
Strange import failure on RHEL 7

### ISSUE THREAD

**Issue by capn-freako** [enthought/enable#887]
Since updating my `enable` installation to `5.2.1`, via building from source, I'm getting the following strange import error, only on RHEL 7. I don't get this error when running under MacOS.

```
    import enable.savage.svg.css
  File "foo/lib/python3.8/site-packages/enable/savage/svg/css/__init__.py", line 10, in <module>
    from .transform import transformList
  File "foo/lib/python3.8/site-packages/enable/savage/svg/css/transform.py", line 18, in <module>
    from enable.savage.svg.pathdata import number, maybeComma
  File "foo/lib/python3.8/site-packages/enable/savage/svg/pathdata.py", line 117, in <module>
    lineTo = Group(Command("L") + Arguments(coordinatePairSequence))
  File "foo/lib/python3.8/site-packages/enable/savage/svg/pathdata.py", line 29, in Command
    return CaselessPreservingLiteral(char)
  File "foo/lib/python3.8/site-packages/enable/savage/svg/pathdata.py", line 43, in __init__
    self.name = "'%s'" % matchString
AttributeError: can't set attribute
```

**Comment by rahulporuri** [comment]
thanks for the report @capn-freako . 

ref https://github.com/enthought/enable/blob/78d2e494097fac71cc5c73efef5fb464963fb4db/enable/savage/svg/pathdata.py#L36-L43

`CaselessPreservingLiteral` inherits from `pyparsing.CaselessLiteral` and the `name` attribute seems to belong to the pyparsing class. Can you report what versions of pyparsing you are using on RHEL7 and MacOS?

**Comment by capn-freako** [comment]
pyparsing versions:

RHEL: 3.0.4

MacOS: 2.4.7

**Comment by rahulporuri** [comment]
> RHEL: 3.0.4

Can I ask whether this behaviour persists if you downgrade `pyparsing` to a version < 3 on RHEL?

**Comment by rahulporuri** [comment]
> RHEL: 3.0.4

I don't see anything in version 3 of `pyparsing` which might be causing this issue - https://pyparsing-docs.readthedocs.io/en/latest/whats_new_in_3_0_0.html.

**Comment by capn-freako** [comment]
Okay, thanks!

I’ve asked the engineer I’m working with to fall back to v2.4.7 of pyparsing and report back.

In the meantime, is it possible that `name` became a read-only property of pyparsing with the release of version 3?

Thanks,
-db

**Comment by rahulporuri** [comment]
> In the meantime, is it possible that `name` became a read-only property of pyparsing with the release of version 3?

Spot on.

https://github.com/pyparsing/pyparsing/blob/0352555d968f9952800f0728383de8e1f9526e1e/pyparsing/core.py#L1802-L1805

`CaselessLiteral` inherits from `Token` which inherits from `ParserElement`. `name` is a property on `ParserElement`. Looks like the right way to set/update `name` on a `CaselessLiteral` is now using the `ParserElement.set_name` method.

**Comment by rahulporuri** [comment]
@capn-freako https://github.com/enthought/enable/pull/888 should fix the issue. Will you be able to test the fix?

**Comment by capn-freako** [comment]
Hi @rahulporuri ,

Sorry for the delay.
Yes, your commit has fixed the problem.

Thanks!
-db
