### ISSUE TITLE
draw_marker_at_points raises if given a size of NaN

### ISSUE THREAD

**Issue by mdickinson** [enthought/enable#902]
I just encountered a segfault in an application as a result of a floating-point NaN accidentally getting passed for the `size` parameter to [`draw_marker_at_points`](https://github.com/enthought/enable/blob/966f062094cb7811db74587d1a7b059ad344f042/kiva/agg/src/graphics_context.i#L778) in `agg.py`. While the NaN was clearly a bug, it would be good to avoid a crash in this situation.

Working on a reproducer.

**Comment by corranwebster** [comment]
Possible work-around: do you have the same issue if you switch to using the `celiagg` backend?

**Comment by mdickinson** [comment]
> do you have the same issue if you switch to using the `celiagg` backend?

Yes, it looks like it:
```python
Traceback (most recent call last):
  File "basic_draw.py", line 52, in <module>
    gc.draw_marker_at_points(points, marker_size, kiva.api.SQUARE_MARKER)
  File "/Users/mdickinson/.edm/envs/enable-test-3.6-null/lib/python3.6/site-packages/kiva/celiagg.py", line 869, in draw_marker_at_points
    points_array, size, marker, fill, stroke
  File "kiva/_marker_renderer.pyx", line 50, in kiva._marker_renderer.MarkerRendererBase.draw_markers
ValueError: cannot convert float NaN to integer
```

**Comment by mdickinson** [comment]
It's looking as though the segfault is not coming from enable, but from Qt at some level. At a guess, the `ValueError` above leaves things in an inconsistent state in the client code. Here's the main thread call stack I get from a macOS crash report:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff203df92e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff2040e5bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff20363406 abort + 125
3   libQt5Core.5.12.6.dylib       	0x000000011c6f7129 0x11c6df000 + 98601
4   libQt5Core.5.12.6.dylib       	0x000000011c6f89b3 QMessageLogger::fatal(char const*, ...) const + 233
5   QtCore.so                     	0x000000011c5429c5 pyqt5_err_print() + 821
```

**Comment by mdickinson** [comment]
Okay, this probably isn't actually an Enable issue. I'll close here, and try to come up with a self-contained reproducer for the segfault.
