### ISSUE TITLE
Kiva AGG renderer breaks when compiled with gcc 4.7+

### ISSUE THREAD

**Issue by jwiggins** [enthought/enable#97]
https://mail.enthought.com/pipermail/enthought-dev/2013-February/032139.html

**Comment by corranwebster** [comment]
The suspect image accessor functions above are part of the original agg codebase.  It's interesting to note that the forked version of agg 2.4 at http://sourceforge.net/projects/agg/ (warning: on SourceForge) has removed the `const` nature of these constructors (see http://sourceforge.net/p/agg/svn/94/ for the appropriate change) to avoid problems with dangling references.

**Comment by jdeschenes** [comment]
This issue is now resolved with #288.

**Comment by jwiggins** [comment]
This should probably be closed.

**Comment by jwiggins** [comment]
This is fixed.
