### ISSUE TITLE
the testsuite (current) still leads up the garden path

### ISSUE THREAD

**Issue by idella** [enthought/enable#99]
I really have trouble getting my head around this one.
4.2 has been around since around early October and this is still seemingly undiscovered.
- python2_7: running distutils-r1_run_phase python_test
  ..........................................................................S./usr/lib64/python2.7/unittest/case.py:338: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  RuntimeWarning)
  .........................................................................
  ----------------------------------------------------------------------
  Ran 17 tests in 0.002s

OK
....S.........................................

Ran 1 test in 0.001s

OK
.SSSS..EE
# 

ERROR: test_antialias_bevel (join_stroke_path_test_case.JoinStrokePathTestCase)

---

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/enable-4.2.0-r1/work/enable-4.2.0-python2_7/kiva/agg/tests/join_stroke_path_test_case.py", line 139, in test_antialias_bevel
    line_cap = kiva.CAP_BUTT
AttributeError: 'module' object has no attribute 'CAP_BUTT'

plus a few more

ERROR: Round caps should extend beyond the end of the line.  We

---

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/enable-4.2.0-r1/work/enable-4.2.0-python2_7/kiva/agg/tests/stroke_path_test_case.py", line 207, in test_alias_cap_round
    gc.set_line_cap(kiva.CAP_ROUND)
AttributeError: 'module' object has no attribute 'CAP_ROUND'

plus a few more

ERROR: Square caps should extend beyond the end of the line. by

---

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/enable-4.2.0-r1/work/enable-4.2.0-python2_7/kiva/agg/tests/stroke_path_test_case.py", line 342, in test_alias_cap_square
    gc.set_line_cap(kiva.CAP_SQUARE)
AttributeError: 'module' object has no attribute 'CAP_SQUARE'

X2

ERROR: Failure: ImportError (cannot import name affine)

---

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/loader.py", line 412, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib64/python2.7/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib64/python2.7/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/var/tmp/portage/dev-python/enable-4.2.0-r1/work/enable-4.2.0-python2_7/kiva/tests/affine_test_case.py", line 17, in <module>
    from kiva import affine
ImportError: cannot import name affine

X2

anyways it comes to 

Ran 237 tests in 26.199s

FAILED (SKIP=6, errors=15)

Now I enthought that the etsproxy package might straighten this out, but it's totally unrelated.  I discovered this months ago and just made a patch of rather large proprtions to set it straight. Observe

PATCHES=( "${FILESDIR}"/${PN}-4-rogue-tests.patch \ 
           "${DISTDIR}"/${PN}-4-TestsPaths.patch )

~/cvsPortage/gentoo-x86/dev-python/enable $ ls -ld "${DISTDIR}"/enable-4-TestsPaths.patch
-rw-rw-r-- 1 testuser portage 20524 Jan 10 09:16 /......distfiles/enable-4-TestsPaths.patch
20.5 kb of patch, so hefty I had to take it out of cvs portage.

Run with the patch;
- python2_7: running distutils-r1_run_phase python_compile_all
  >>> Source compiled.
  - python2_7: running distutils-r1_run_phase python_test
    ..........................................................................S./usr/lib64/python2.7/unittest/case.py:338: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
    RuntimeWarning)
    .........................................................................
    ----------------------------------------------------------------------
    Ran 17 tests in 0.002s

OK
....S........................................./var/tmp/portage/dev-python/enable-4.2.0-r1/work/enable-4.2.0-python2_7/build/lib/kiva/fonttools/font_manager.py:1290: UserWarning: findfont: Font family ['modern'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
## ...................................................

Ran 1 test in 0.001s

OK
.SSSS......................................................

---

Ran 287 tests in 24.720s

OK (SKIP=6)

Ahhh the sweet taste of success.  Note 287 tests, so nosetests has captured the various tests folders of the source.

---

 ~/cvsPortage/gentoo-x86/dev-python/enable $ grep CAP_BUTT -r /var/tmp/portage/dev-python/enable-4.2.0-r1/work/ | grep kiva | grep = |grep agg.py
yields
/.................../build/lib/kiva/agg/agg.py:CAP_BUTT = _agg.CAP_BUTT

With the exception of affeine, all above errors from 1 thru 13 come from import statements the ilk of 
from kiva.agg import GraphicsContextArray
import kiva

and without exception the paths are wrong. The imports I'm only guessing manage to import kiva.agg by implication, I really don't know, since that's what they need to import despite the absence of "from kiva import agg"

The patch comprises many instances of the ilk;
-        line_cap = kiva.CAP_BUTT
-        line_join = kiva.JOIN_MITER
-        line_cap = kiva.agg.CAP_BUTT
-        line_join = kiva.agg.JOIN_MITER

Now am I missing something here, or does the enable package have import paths pointing to kiva and not kiva/agg which is the holder of all the cited missing funcs in agg,py plus affeine.py in the kiva/agg folder??????????????????

affeine also doesn't import and this is a curious oddity since the import statements appears quite valid
"from kiva import affine"
affeine.py is indeed in the folder of kiva.  This weirdness is perhaps some python intricacy I don't know about re how python does imports.  Although it should work, it doesn't, and for whatever silly reason, on my system, it gets there with 
"+from kiva.constants import *"
which I think is recognised as poor style.

**Comment by rahulporuri** [comment]
closing as this issue is now outdated given the large number of changes made to the testsuite - we dont use nose to discover/run the testsuite, we renamed the test modules to start with `test_` so that they get discovered by unittest. At the moment, we are not seeing any test failures or undiscovered tests on master.
