### ISSUE TITLE
Remove uses of 0 and 1 for `True` and `False` in Python code

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#992]
Because Python 2.3 came out nearly 20 years ago.  I think we're safe to make the switch :)

**Comment by homosapien-lcy** [comment]
I haven't found any cases of using 0 and 1 for True and False in the Python code

**Comment by corranwebster** [comment]
I think this issue may have been fixed last year as part of another PR and not closed.  I'll close it.

Thanks for checking.
